// (c) Meta Platforms, Inc. and affiliates. Confidential and proprietary.
// Copyright Epic Games, Inc. All Rights Reserved.
#include "MetaXRAcousticGeometry.h"
#include "AudioDevice.h"
#include "Engine/StaticMesh.h"
#include "HAL/FileManager.h"
#include "HAL/PlatformFileManager.h"
#include "IMetaXRAudioPlugin.h"
#include "Kismet/KismetMathLibrary.h"
#include "Landscape.h"
#include "LandscapeComponent.h"
#include "LandscapeDataAccess.h"
#include "LandscapeInfo.h"
#include "Materials/MaterialInstanceDynamic.h"
#include "MetaXRAcousticMaterial.h"
#include "MetaXRAcousticProjectSettings.h"
#include "MetaXRAudioUtilities.h"
#ifdef META_NATIVE_UNREAL_PLUGIN
#include "MetaXRAudioContextManager.h"
#endif
#include "MetaXR_Audio.h"
#include "Misc/FileHelper.h"
#include "Runtime/Core/Public/Serialization/CustomVersion.h"
#include "StaticMeshResources.h"

#include "Misc/EngineVersionComparison.h"
#if UE_VERSION_OLDER_THAN(5, 2, 0)
#include "MaterialShared.h"
#else
#include "Materials/MaterialRenderProxy.h"
#endif

#define COMPILE_AS_DEBUG_MODE 0

#if COMPILE_AS_DEBUG_MODE
#pragma optimize("", off) // worse perf, better debugging
#endif

#define UE_ACOUSTIC_GEOMETRY_COMPONENT_LATEST_VERSION 1
#define WITH_EDITOR_GIZMOS (WITH_EDITOR && WITH_EDITORONLY_DATA)

// Forward declare hidden function
ovrResult ovrAudio_AudioGeometrySetObjectFlag(ovrAudioGeometry geometry, ovrAudioObjectFlags flag, int32_t enabled);

#if WITH_EDITOR
#define UE_ACOUSTIC_GEO_FILE_EXTENSION ".xrageo"
void UMetaXRAcousticGeometry::GenerateFileNameIfEmpty() {
  if (!FilePath.IsEmpty() || GetOwner() == nullptr) {
    return;
  }
  MetaXRAudioUtilities::CreateMetaXRAcousticContentDirectory(META_XR_AUDIO_DEFAULT_SAVE_FOLDER);
  FilePath = FPaths::Combine(META_XR_AUDIO_DEFAULT_SAVE_FOLDER, GetOwner()->GetActorLabel() + UE_ACOUSTIC_GEO_FILE_EXTENSION);
  UE_LOG(LogAudio, Display, TEXT("No file path specified, using the autogenerated name of: %s"), *FilePath);
}
#endif

static const FGuid UMetaXRAcousticGeometryGUID(0x7aa25489, 0x40d74392, 0xad87d336, 0x347cfae2); // random GUID, guaranteed to be random.
static const FCustomVersionRegistration UMetaXRAcousticGeometryGUIDRegistration(
    UMetaXRAcousticGeometryGUID,
    UE_ACOUSTIC_GEOMETRY_COMPONENT_LATEST_VERSION,
    TEXT("MetaXRAcousticGeometryVersion"));

UMetaXRAcousticGeometry::UMetaXRAcousticGeometry() : DataSize(0), OvrGeometry(nullptr), CachedContext(nullptr) {
  bAutoActivate = true;
  PrimaryComponentTick.bCanEverTick = true;
  bWantsInitializeComponent = true;
  bTickInEditor = true;
}

UMetaXRAcousticGeometry::~UMetaXRAcousticGeometry() {}

bool UMetaXRAcousticGeometry::IsStatic() {
  if (GetOwner()) {
    return (GetOwner()->FindComponentByClass<UStaticMeshComponent>() != nullptr);
    // return Mobility != EComponentMobility::Movable;
  }
  return false;
}

// We do not allow UGeometry transformations as we want our geometry to stay in sync with the Static Mesh
void UMetaXRAcousticGeometry::CheckGeoTransformValid() {
  if (GetOwner() == nullptr) {
    return;
  }
  if (!GetOwner()->GetTransform().Equals(GetComponentTransform())) {
    ResetRelativeTransform();
    UE_LOG(
        LogAudio,
        Warning,
        TEXT(
            "You cannot change the transform of the UGeometry, only the transform of your static mesh or landscape. This ensures the audio geometry stays in sync with the physical geometry."));
  }
}

static TArray<FString> GetExcludeTags() {
  const UMetaXRAcousticProjectSettings* Settings = GetDefault<UMetaXRAcousticProjectSettings>();
  return Settings->ExcludeTags;
}

// Implement the visitor classes
// Age checker and IsOlder function can check if the meshes have changed since the last bake
UMetaXRAcousticGeometry::FAgeChecker::FAgeChecker(FDateTime TimeStamp) {
  this->TimeStamp = TimeStamp;
}

void* UMetaXRAcousticGeometry::FAgeChecker::Visit(AActor* Transform, void* UserData) {
  TArray<UStaticMeshComponent*> MeshComponents;
  Transform->GetComponents<UStaticMeshComponent>(MeshComponents);
  for (UStaticMeshComponent* MeshComponent : MeshComponents) {
    UStaticMesh* Mesh = MeshComponent->GetStaticMesh();

    FString relativeMeshPath = Mesh->GetPathName();
    FString AbsoluteMeshPath = relativeMeshPath.Replace(TEXT("/Game/"), *FPaths::ProjectContentDir());
    AbsoluteMeshPath = FPaths::SetExtension(AbsoluteMeshPath, TEXT(".uasset"));
    IPlatformFile& PlatformFile = FPlatformFileManager::Get().GetPlatformFile();
    FDateTime lastModified =
        PlatformFile.FileExists(*AbsoluteMeshPath) ? IFileManager::Get().GetTimeStamp(*AbsoluteMeshPath) : FDateTime::MinValue();

    // UE_LOG(LogAudio, Warning, TEXT("modified %s, last build %s"), *lastModified.ToString(), *timeStamp.ToString());
    if (lastModified > TimeStamp) {
      // UE_LOG(LogAudio, Warning, TEXT("Newer mesh file %s"), *AbsoluteMeshPath);
      bIsOlder = true; // mesh file changed
      return nullptr;
    }
  }
  return nullptr;
}

bool UMetaXRAcousticGeometry::IsOlder(FDateTime TimeStamp) {
  FAgeChecker AgeChecker(TimeStamp);
  TraverseMeshHierarchy(GetOwner(), bIncludeChildren, GetExcludeTags(), false, LOD, AgeChecker);
  return AgeChecker.bIsOlder;
}

UMetaXRAcousticGeometry::FHashAppender::FHashAppender(FString Hash) {
  this->Hash = Hash;
}

void* UMetaXRAcousticGeometry::FHashAppender::Visit(AActor* Transform, void* UserData) {
  // Unreal FMD5Hash only accepts string, so convert to string first
  FString stringRepresentation = FString::Printf(
      TEXT("%f%f%f%f%f%f%f%f%f%f"),
      Transform->GetTransform().GetTranslation().X,
      Transform->GetTransform().GetTranslation().Y,
      Transform->GetTransform().GetTranslation().Z,
      Transform->GetTransform().GetRotation().W,
      Transform->GetTransform().GetRotation().X,
      Transform->GetTransform().GetRotation().Y,
      Transform->GetTransform().GetRotation().Z,
      Transform->GetTransform().GetScale3D().X,
      Transform->GetTransform().GetScale3D().Y,
      Transform->GetTransform().GetScale3D().Z);
  Hash = FMD5::HashAnsiString(*stringRepresentation);

  return nullptr;
}

void UMetaXRAcousticGeometry::AppendHash(FString& Hash) {
  FHashAppender hashAppender(*Hash);
  TraverseMeshHierarchy(GetOwner(), bIncludeChildren, GetExcludeTags(), false, LOD, hashAppender);
  Hash.Append(hashAppender.Hash);
}

UMetaXRAcousticGeometry::FMeshGatherer::FMeshGatherer(bool bIgnoreStatic, int LODSelection) {
  this->bIgnoreStatic = bIgnoreStatic;
  this->LodSelection = LODSelection;
}

void* UMetaXRAcousticGeometry::FMeshGatherer::Visit(AActor* Transform, void* UserData) {
  TArray<UMetaXRAcousticMaterial*> CurrentMaterials = *(TArray<UMetaXRAcousticMaterial*>*)UserData;
  TArray<UStaticMeshComponent*> MeshComponents;
  Transform->GetComponents<UStaticMeshComponent>(MeshComponents);
  ALandscape* LandscapeActor = Cast<ALandscape>(Transform);
  TArray<UMetaXRAcousticMaterial*> AcousticMaterials;
  Transform->GetComponents<UMetaXRAcousticMaterial*>(AcousticMaterials);

  // Initialize the current material array to a new array if there are any new materials.
  if (AcousticMaterials.Num() > 0) {
    // Determine the length of the material array.
    int MaxLength = AcousticMaterials.Num();
    if (CurrentMaterials.Num() > 0) {
      MaxLength = FMath::Max(MaxLength, CurrentMaterials.Num());
    }

    TArray<UMetaXRAcousticMaterial*> NewMaterials;
    NewMaterials.SetNumUninitialized(MaxLength);

    // Copy the previous materials into the new array.
    if (CurrentMaterials.Num() > 0) {
      for (int i = AcousticMaterials.Num(); i < MaxLength; i++) {
        NewMaterials[i] = CurrentMaterials[i];
      }
    }
    CurrentMaterials = NewMaterials;

    // Copy the current materials.
    for (int i = 0; i < AcousticMaterials.Num(); i++) {
      CurrentMaterials[i] = AcousticMaterials[i];
    }
  }

  // Gather the meshes.
  for (UStaticMeshComponent* MeshComponent : MeshComponents) {
    UStaticMesh* Mesh = MeshComponent->GetStaticMesh();
    if (!Mesh)
      continue;

    if (bIgnoreStatic &&
        ((MeshComponent->Mobility == EComponentMobility::Static) || (MeshComponent->Mobility == EComponentMobility::Stationary))) {
      UE_LOG(LogAudio, Error, TEXT("Mesh not readable. Use \"File Enabled\" for static geometry"));
      ++IgnoredMeshCount;
      continue;
    }

    int32 LodGroupToUse = FMath::Clamp(LodSelection, 0, Mesh->GetRenderData()->LODResources.Num() - 1);
    FStaticMeshLODResources& Model = Mesh->GetRenderData()->LODResources[LodGroupToUse];
    UMetaXRAcousticGeometry::FMeshMaterial MeshMat;
    MeshMat.StaticMesh = MeshComponent;
    MeshMat.LOD = LodGroupToUse;
    MeshMat.Materials = CurrentMaterials;
    Meshes.Add(MeshMat);
  }

  // Gather the terrains.
#if WITH_EDITOR
  if (LandscapeActor) {
    UMetaXRAcousticGeometry::FLandscapeMaterial LandscapeMat;
    LandscapeMat.Materials = CurrentMaterials;
    LandscapeMat.LandscapeInfo = LandscapeActor->CreateLandscapeInfo();
    if (LandscapeMat.LandscapeInfo == nullptr) {
      UE_LOG(LogAudio, Warning, TEXT("Unabled to create audio propagation geometry for landscape, landscape info not found!"));
    } else {
      Terrains.Add(LandscapeMat);
    }
  }
#endif

  // Check if there a BSP is used and warn the user we don't support it at this time
  ABrush* brush = Cast<ABrush>(Transform);
  if (brush != nullptr) {
    UE_LOG(
        LogAudio,
        Warning,
        TEXT(
            "Detected using Meta XR Audio on a BSP component. The plugin doesn't support BSPs at this time and will not be included in the geometry"));
  }

  // Update the persistent parent data
  *(TArray<UMetaXRAcousticMaterial*>*)UserData = CurrentMaterials;
  return UserData;
}

// Implement the visitor classes

void UMetaXRAcousticGeometry::OnRegister() {
  Super::OnRegister();

#if WITH_EDITOR
  GenerateFileNameIfEmpty();
#endif
  CheckGeoTransformValid();

  if (!MetaXRAudioUtilities::PlayModeActive(GetWorld())) {
    // This will update the visualizer on startup but keep the geo handle empty for editor
    // Note this is called whenever transform information is changed, but we only do this in editor if we have nothing
    if (SimplifiedVertices.Num() == 0) {
      StartInternal();
      DestroyInternal();
    }
  } else {
    // Start up the geometry when play starts, it will be destroyed when the game ends at unregister
    StartInternal();
  }
}

void UMetaXRAcousticGeometry::OnUnregister() {
  Super::OnUnregister();
  DestroyInternal();
}

bool UMetaXRAcousticGeometry::StartInternal() {
  if (!CreatePropagationGeometry()) {
    UE_LOG(LogAudio, Warning, TEXT("Failed to setup geometry component"));
    return false;
  }
  ApplyTransform();
  return true;
}

bool UMetaXRAcousticGeometry::CreatePropagationGeometry() {
#ifdef META_NATIVE_UNREAL_PLUGIN
  CachedContext = FMetaXRAudioContextManager::GetContext(GetOwner(), GetWorld());
  if (CachedContext == nullptr) {
    UE_LOG(
        LogAudio,
        Warning,
        TEXT(
            "Unable to get Meta XR Audio Context. Please check that the Spatialization Plugin and Reverb Plugin are set to Meta XR Audio in project settings. Restart the project after setting."));
#else
  CachedContext = FMetaXRAudioLibraryManager::Get().GetPluginContext();
  if (CachedContext == nullptr) {
    UE_LOG(
        LogAudio,
        Warning,
        TEXT("Unable to get Meta XR Audio Context. Please check the Meta XR Audio binaries have been placed correctly."));
#endif
    return false;
  }

  if (OvrGeometry != nullptr) {
    UE_LOG(LogAudio, Warning, TEXT("Tried to initialize geometry twice, destroying stale copy"));
    DestroyPropagationGeometry();
  }

  if (OvrGeometry != nullptr) {
    UE_LOG(LogAudio, Warning, TEXT("Unable to clean up stale geometry"));
    return false;
  }

  // our internal geometry object into which we'll merge this static mesh actor and all its attached meshes
  ovrResult Result = OVRA_CALL(ovrAudio_CreateAudioGeometry)(CachedContext, &OvrGeometry);
  if (Result != ovrSuccess) {
    UE_LOG(LogAudio, Warning, TEXT("Failed creating acoustic geometry object."));
    return false;
  } else {
    UE_LOG(LogAudio, Log, TEXT("Created new geometry handle %p"), OvrGeometry);
  }

#if WITH_EDITOR
  if (!MetaXRAudioUtilities::PlayModeActive(GetWorld())) {
    // If this is startup during project startup, try loading an existing file before uploading because we don't have access to child meshes
    // at Startup time
    bool FileReadSuccessfully = false;
    if (!SimplifiedVertices.Num() && bFileEnabled) {
      FileReadSuccessfully = ReadFile();
    }

    if (!FileReadSuccessfully && !UploadMesh(OvrGeometry)) {
      return false;
    }
    UpdateGizmoMesh();
  } else
#endif
      if (bFileEnabled) {
    if (!ReadFile()) {
      return false;
    }
  } else {
    if (IsStatic()) {
      UE_LOG(LogAudio, Warning, TEXT("Static geometry requires \"File Enabled\""));
      return false;
    } else if (!UploadGeometry()) {
      return false;
    }
  }

  return true;
}

// ------------------------------------------------------------------------------------------------------------------------------------------------------------
// Note: a child (attached) static mesh will have it's geometry merged into the parent. Therefore, its ovrGeometry data member will be
// nullptr below and this is why we need the Uploaded member.
void UMetaXRAcousticGeometry::TickComponent(float DeltaTime, enum ELevelTick TickType, FActorComponentTickFunction* ThisTickFunction) {
  Super::TickComponent(DeltaTime, TickType, ThisTickFunction);
  if (OvrGeometry != nullptr) {
    FTransform Transform = GetComponentTransform();
    if (!Transform.Equals(PreviousTransform) || (PreviousGeometry != OvrGeometry)) {
      ApplyTransform();
    }
#if WITH_EDITOR_GIZMOS
    if (!MetaXRAudioUtilities::PlayModeActive(GetWorld())) {
      UpdateGizmoMesh();
    }
#endif
  }
}

// ------------------------------------------------------------------------------------------------------------------------------------------------------------
bool UMetaXRAcousticGeometry::UploadGeometry() {
  int IgnoredMeshCount = 0;
  if (!UploadMesh(OvrGeometry, GetOwner(), MetaXRAudioUtilities::PlayModeActive(GetWorld()), IgnoredMeshCount)) {
    return false;
  }

  if (IgnoredMeshCount != 0) {
    UE_LOG(
        LogAudio,
        Warning,
        TEXT("Failed to upload meshes, %i static meshes ignored. Turn on \"File Enabled\" to process static meshes offline"),
        IgnoredMeshCount);
  }

#if WITH_EDITOR
  UpdateGizmoMesh();
#endif
  return true;
}

static void UpdateCountsForMesh(
    int32& TotalVertexCount,
    uint32& TotalIndexCount,
    int32& TotalFaceCount,
    int32& TotalMaterialCount,
    UStaticMeshComponent* MeshComponent,
    int32 LOD) {
  if (!MeshComponent)
    return;

  UStaticMesh* Mesh = MeshComponent->GetStaticMesh();
  if (!Mesh)
    return;

  int32 LodGroupToUse = FMath::Clamp(LOD, 0, Mesh->GetRenderData()->LODResources.Num() - 1);
  FStaticMeshLODResources& Model = Mesh->GetRenderData()->LODResources[LodGroupToUse];
  const FPositionVertexBuffer& VertexBuffer = Model.VertexBuffers.PositionVertexBuffer;

  TotalVertexCount += VertexBuffer.GetNumVertices();
  TotalIndexCount += Model.IndexBuffer.GetNumIndices();
  TotalFaceCount += Model.IndexBuffer.GetNumIndices() / 3;
  TotalMaterialCount += Mesh->GetNumSections(LOD);
}

#if WITH_EDITOR
static void UpdateCountsForLandscape(
    int32& TotalVertexCount,
    uint32& TotalIndexCount,
    int32& TotalFaceCount,
    int32& TotalMaterialCount,
    ULandscapeInfo* LandscapeInfo,
    int32 LOD) {
  if (!LandscapeInfo)
    return;

  for (auto It = LandscapeInfo->XYtoComponentMap.CreateIterator(); It; ++It) {
    ULandscapeComponent* Component = It.Value();
    const int32 Length = Component->ComponentSizeQuads + 1;
    TotalVertexCount += (Length * Length);
    TotalIndexCount += 4 * (Length - 1) * (Length - 1);
  }

  TotalMaterialCount += 1;
}
#endif

static bool UploadMeshFilter(
    ovrAudioContext Context,
    TArray<ovrAudioMeshGroup>& MeshGroups,
    TArray<FVector>& Vertices,
    TArray<uint32>& Indices,
    int32& VertexOffset,
    int32& IndexOffset,
    int32& GroupOffset,
    UStaticMesh* Mesh,
    int32 LOD,
    TArray<UMetaXRAcousticMaterial*>& Materials,
    FMatrix Matrix) {
  // Lowest LOD
  int32 LodGroupToUse = FMath::Clamp(LOD, 0, Mesh->GetRenderData()->LODResources.Num() - 1);
  const FStaticMeshLODResources& Model = Mesh->GetRenderData()->LODResources[LodGroupToUse];
  const FPositionVertexBuffer& VertexBuffer = Model.VertexBuffers.PositionVertexBuffer;
  const int32 VertexCount = VertexBuffer.GetNumVertices();

  // append this mesh's vertices to the merged array after coordinate system conversion
  for (int32 Index = 0; Index < VertexCount; Index++) {
    int32 Offset = (VertexOffset + Index);
    FVector TransformedVertex = UKismetMathLibrary::Matrix_TransformPosition(Matrix, (FVector)VertexBuffer.VertexPosition(Index));
    Vertices[Offset] = MetaXRAudioUtilities::ToOVRVector(TransformedVertex);
  }
  const int32 IndexCount = Model.IndexBuffer.GetNumIndices();
  for (int32 Index = 0; Index < IndexCount; Index++) {
    Indices[IndexOffset + Index] = Model.IndexBuffer.GetIndex(Index) + VertexOffset;
  }

  // loop over each section in lowest LOD
  for (int32 Index = 0; Index < Model.Sections.Num(); Index++) {
    ovrAudioMeshGroup& MeshGroup = MeshGroups[GroupOffset + Index];
    MeshGroup.faceCount = Model.Sections[Index].NumTriangles;
    MeshGroup.faceType = ovrAudioFaceType_Triangles;
    MeshGroup.indexOffset = Model.Sections[Index].FirstIndex + IndexOffset;

    ovrAudioMaterial OvrMaterial = nullptr;
    if (!Materials.IsEmpty()) {
      ovrResult Result = OVRA_CALL(ovrAudio_CreateAudioMaterial)(Context, &OvrMaterial);
      if (Result != ovrSuccess) {
        return false;
      }

      int MatIndex = Index;
      if (MatIndex >= Materials.Num())
        MatIndex = Materials.Num() - 1;

      Materials[MatIndex]->ConstructMaterial(OvrMaterial);
    }
    MeshGroup.material = OvrMaterial;
  }

  // Update the offsets for the next meshs
  VertexOffset += VertexCount;
  IndexOffset += IndexCount;
  GroupOffset += Model.Sections.Num();

  return true;
}

#if WITH_EDITOR
static bool UploadLandscapeFilter(
    ovrAudioContext Context,
    TArray<ovrAudioMeshGroup>& MeshGroups,
    TArray<FVector>& Vertices,
    TArray<uint32>& Indices,
    int32& VertexOffset,
    int32& IndexOffset,
    int32& GroupOffset,
    UMetaXRAcousticGeometry::FLandscapeMaterial Landscape,
    FMatrix WorldToLocal) {
  int32 FirstIndex = IndexOffset;
  int32 FaceCount = 0;
  for (auto It = Landscape.LandscapeInfo->XYtoComponentMap.CreateIterator(); It; ++It) {
    ULandscapeComponent* Component = It.Value();

    // Compute the combined transform to go from mesh-local to geometry-local space.
    FMatrix localMatrix = UKismetMathLibrary::Conv_TransformToMatrix(Component->GetComponentTransform());
    FMatrix Matrix = UKismetMathLibrary::Multiply_MatrixMatrix(localMatrix, UKismetMathLibrary::Matrix_GetInverse(WorldToLocal));

    FLandscapeComponentDataInterface DataInterface(Component);
    const int Offset = VertexOffset;
    const int Length = Component->ComponentSizeQuads + 1;

    for (auto y = 0; y < Length; ++y) {
      for (auto x = 0; x < Length; ++x) {
        FVector vertex = DataInterface.GetLocalVertex(x, y);
        Vertices[VertexOffset++] = MetaXRAudioUtilities::ToOVRVector(UKismetMathLibrary::Matrix_TransformPosition(Matrix, vertex));

        // there are only (N-1)^2 quads for N^2 verts
        if (x == (Length - 1) || y == (Length - 1))
          continue;

        auto calcIndex = [](int x, int y, int length) { return (y * length) + x; };
        Indices[IndexOffset + 0] = Offset + calcIndex(x, y, Length);
        Indices[IndexOffset + 1] = Offset + calcIndex(x, y + 1, Length);
        Indices[IndexOffset + 2] = Offset + calcIndex(x + 1, y + 1, Length);
        Indices[IndexOffset + 3] = Offset + calcIndex(x + 1, y, Length);

        IndexOffset += 4;
        ++FaceCount;
      }
    }
  }

  ovrAudioMaterial OvrMaterial = nullptr;
  if (!Landscape.Materials.IsEmpty()) {
    ovrResult Result = OVRA_CALL(ovrAudio_CreateAudioMaterial)(Context, &OvrMaterial);
    if (Result != ovrSuccess) {
      UE_LOG(LogAudio, Warning, TEXT("Unabled to create audio material for landscape!"));
      return false;
    }
    Landscape.Materials[0]->ConstructMaterial(OvrMaterial);
  }

  ovrAudioMeshGroup& MeshGroup = MeshGroups[GroupOffset++];
  MeshGroup.faceCount = FaceCount;
  MeshGroup.faceType = ovrAudioFaceType_Quads;
  MeshGroup.material = OvrMaterial;
  MeshGroup.indexOffset = FirstIndex;

  return true;
}
#endif

void UMetaXRAcousticGeometry::TraverseMeshHierarchy(
    AActor* Actor,
    bool IncludeChildren,
    TArray<FString> ExcludeTags,
    bool parentWasExcluded,
    int LodSelection,
    ITransformVisitor& Visitor,
    void* ParentData) {
  if (Actor == nullptr) {
    // UE_LOG(LogAudio, Error, TEXT("Geometry cannot be analyzed as this component has no owner"));
    return;
  }

  // Begin analysis of whether to visit this component or not
  bool bShouldVisit = true;
  if (parentWasExcluded) {
    UE_LOG(LogAudio, Log, TEXT("Skipping Object %s based on excluded parent"), *Actor->GetActorNameOrLabel());
    bShouldVisit = false;
  }

  // Check if an exclude tag matches this component and do not visit if so
  for (FName ActorTag : Actor->Tags) {
    if (ExcludeTags.Contains(ActorTag.ToString())) {
      UE_LOG(LogAudio, Log, TEXT("Skipping Object %s based on exclude tag: %s"), *Actor->GetActorNameOrLabel(), *ActorTag.ToString());
      bShouldVisit = false;
      break;
    }
  }

  // We should override exclude tags if there is a material on this child component
  TArray<UMetaXRAcousticMaterial*> AcousticMaterials;
  Actor->GetComponents<UMetaXRAcousticMaterial*>(AcousticMaterials);
  if (!AcousticMaterials.IsEmpty()) {
    UE_LOG(LogAudio, Log, TEXT("Override exclude tag due to presence of acoustic material in child %s"), *Actor->GetActorNameOrLabel());
    bShouldVisit = true;
  }

  if (bShouldVisit) {
    ParentData = Visitor.Visit(Actor, ParentData);
  }

  if (IncludeChildren) {
    TArray<AActor*> AttachedActors;
    Actor->GetAttachedActors(AttachedActors);
    for (AActor* Child : AttachedActors) {
      UMetaXRAcousticGeometry* ChildAcousticGeometry = Child->FindComponentByClass<UMetaXRAcousticGeometry>();
      if (!ChildAcousticGeometry) {
        TraverseMeshHierarchy(Child, IncludeChildren, ExcludeTags, !bShouldVisit, LodSelection, Visitor, ParentData);
      } else {
        UE_LOG(
            LogAudio,
            Display,
            TEXT("Skipping child: %s, it has its own UMetaXRAcousticGeometry component"),
            *ChildAcousticGeometry->GetOwner()->GetName());
      }
    }
  }
}

bool UMetaXRAcousticGeometry::UploadMesh(ovrAudioGeometry GeometryHandle) {
  int32 IgnoredMeshCount = 0;
  return UploadMesh(GeometryHandle, GetOwner(), false, IgnoredMeshCount);
}

bool UMetaXRAcousticGeometry::UploadMesh(
    ovrAudioGeometry GeometryHandle,
    AActor* Owner,
    bool IgnoreStatic,
    int& OutIgnoredMeshCount) { // output parameter
  OutIgnoredMeshCount = 0;
  if (CachedContext == nullptr)
    return false;

  CheckGeoTransformValid();

  // Get the child mesh objects.
  FMeshGatherer Gatherer = FMeshGatherer(IgnoreStatic, LOD);

  // Find all the mesh information attached and child to this componentd
  TArray<UMetaXRAcousticMaterial*> CurrentMaterials;
  TraverseMeshHierarchy(Owner, bIncludeChildren, GetExcludeTags(), false, LOD, Gatherer, &CurrentMaterials);

  int32 TotalVertexCount = 0;
  uint32 TotalIndexCount = 0;
  int32 TotalFaceCount = 0;
  int32 TotalMaterialCount = 0;

  // Update the counts for all static meshes
  for (FMeshMaterial& MeshMaterial : Gatherer.GetMeshes())
    UpdateCountsForMesh(TotalVertexCount, TotalIndexCount, TotalFaceCount, TotalMaterialCount, MeshMaterial.StaticMesh, LOD);

#if WITH_EDITOR
  // Update the counts for all landscapes
  for (FLandscapeMaterial& LandscapeMaterial : Gatherer.GetTerrains())
    UpdateCountsForLandscape(TotalVertexCount, TotalIndexCount, TotalFaceCount, TotalMaterialCount, LandscapeMaterial.LandscapeInfo, LOD);
#endif

  TArray<ovrAudioMeshGroup> MeshGroups{};
  MeshGroups.SetNumUninitialized(TotalMaterialCount);
  TArray<FVector> Vertices{};
  Vertices.SetNumUninitialized(TotalVertexCount);
  TArray<uint32> Indices{};
  Indices.SetNumUninitialized(TotalIndexCount);

  int32 VertexOffset = 0;
  int32 IndexOffset = 0;
  int32 GroupOffset = 0;

  // Append each static meshes details to the aggregate arrays
  FMatrix WorldMatrix = UKismetMathLibrary::Conv_TransformToMatrix(GetComponentTransform());
  for (FMeshMaterial& Mesh : Gatherer.GetMeshes()) {
    UStaticMeshComponent* StaticMeshComponent = Mesh.StaticMesh;

    // Compute the combined transform to go from mesh-local to geometry-local space.
    FMatrix LocalMatrix = UKismetMathLibrary::Conv_TransformToMatrix(StaticMeshComponent->GetComponentTransform());
    FMatrix Matrix = UKismetMathLibrary::Multiply_MatrixMatrix(LocalMatrix, UKismetMathLibrary::Matrix_GetInverse(WorldMatrix));
    if (!UploadMeshFilter(
            CachedContext,
            MeshGroups,
            Vertices,
            Indices,
            VertexOffset,
            IndexOffset,
            GroupOffset,
            StaticMeshComponent->GetStaticMesh(),
            Mesh.LOD,
            Mesh.Materials,
            Matrix)) {
      return false;
    }
  }

#if WITH_EDITOR
  // Append each landscape materials details to the aggregate arrays
  for (FLandscapeMaterial& Landscape : Gatherer.GetTerrains()) {
    if (!UploadLandscapeFilter(
            CachedContext, MeshGroups, Vertices, Indices, VertexOffset, IndexOffset, GroupOffset, Landscape, WorldMatrix)) {
      return false;
    }
  }
#endif

  if (TotalVertexCount == 0) {
    UE_LOG(LogAudio, Error, TEXT("Unable to upload mesh, vertex count is zero %s"), *FilePath);
    return false;
  }

  UE_LOG(LogAudio, Log, TEXT("Uploading mesh %s with %i vertices"), *FilePath, TotalVertexCount);

  float UnitScale = 0.01f;
  ovrAudioMeshSimplification Simplification{};
  Simplification.thisSize = sizeof(ovrAudioMeshSimplification);
  Simplification.flags = static_cast<ovrAudioMeshFlags>(MeshFlags);
  // UI is in centimeters because game units but the ovrAudio API is meters
  Simplification.unitScale = UnitScale;
  Simplification.maxError = MaxError * UnitScale;
  Simplification.minDiffractionEdgeAngle = 1.0f;
  Simplification.minDiffractionEdgeLength = 1.0f * UnitScale;
  Simplification.flagLength = 100.0f * UnitScale;
#if WITH_EDITOR
  Simplification.threadCount = 0; // Use as many threads as CPUs
#else
  Simplification.threadCount = 1;
#endif

  ovrResult Result = OVRA_CALL(ovrAudio_AudioGeometryUploadSimplifiedMeshArrays)(
      GeometryHandle,
      Vertices.GetData(),
      0,
      Vertices.Num(),
      0,
      ovrAudioScalarType_Float64,
      Indices.GetData(),
      0,
      Indices.Num(),
      ovrAudioScalarType_UInt32,
      MeshGroups.GetData(),
      MeshGroups.Num(),
      &Simplification);
  if (Result != ovrSuccess) {
    UE_LOG(LogAudio, Warning, TEXT("Failed adding geometry to the audio propagation sub-system!"));
    return false;
  } else {
    UE_LOG(LogAudio, Log, TEXT("Successfully uploaded geometry %p"), GeometryHandle);
  }

  Result = OVRA_CALL(ovrAudio_AudioGeometrySetObjectFlag)(GeometryHandle, ovrAudioObjectFlag_Enabled, true);
  Result = OVRA_CALL(ovrAudio_AudioGeometrySetObjectFlag)(GeometryHandle, ovrAudioObjectFlag_Static, IsStatic());

  // Clean up native handles
  for (const ovrAudioMeshGroup& Group : MeshGroups) {
    if (Group.material != nullptr) {
      Result = OVRA_CALL(ovrAudio_DestroyAudioMaterial)(Group.material);
      if (Result != ovrSuccess) {
        UE_LOG(LogAudio, Warning, TEXT("Failed to destroy material %p"), GeometryHandle);
      }
    }
  }

  return (Result == ovrSuccess);
}

bool UMetaXRAcousticGeometry::DestroyInternal() {
  if (!DestroyPropagationGeometry()) {
    return false;
  }

  return true;
}

bool UMetaXRAcousticGeometry::DestroyPropagationGeometry() {
  if (OvrGeometry == nullptr) {
    return false;
  }

  UE_LOG(LogAudio, Log, TEXT("Destroying geometry handle %p"), OvrGeometry);
  ovrResult Result = OVRA_CALL(ovrAudio_DestroyAudioGeometry)(OvrGeometry);
  if (Result != ovrSuccess) {
    UE_LOG(LogAudio, Warning, TEXT("Unable to destroy geometry"));
  }
  OvrGeometry = nullptr;

  return true;
}

void UMetaXRAcousticGeometry::ApplyTransform() {
  if (OvrGeometry == nullptr) {
    UE_LOG(LogAudio, Error, TEXT("No ovrGeoemtry for MetaXRAcousticGeometry"));
    return;
  }

  FTransform UETransform = GetComponentTransform();
  TArray<float> OVRTransform = MetaXRAudioUtilities::ConvertUETransformToOVRTransform(UETransform);

  ovrResult Result = OVRA_CALL(ovrAudio_AudioGeometrySetTransform)(OvrGeometry, &OVRTransform[0]);
  if (Result != ovrSuccess) {
    UE_LOG(LogAudio, Log, TEXT("Failed at setting new audio propagation mesh transform!"));
    return;
  } else {
    UE_LOG(LogAudio, Log, TEXT("Set transform for geometry %p"), OvrGeometry);
  }

  PreviousTransform = UETransform;
  PreviousGeometry = OvrGeometry;
}

#if WITH_EDITOR
void UMetaXRAcousticGeometry::UpdateGizmoMesh() {
  UpdateGizmoMesh(OvrGeometry);
}

void UMetaXRAcousticGeometry::UpdateGizmoMesh(ovrAudioGeometry GeometryHandle) {
  if (GeometryHandle == nullptr) {
    UE_LOG(LogAudio, Warning, TEXT("Unable to update gizmo: Geometry not loaded."));
  }

  uint32_t NumVertices, NumTriangles = 0;
  ovrResult Result = OVRA_CALL(ovrAudio_AudioGeometryGetSimplifiedMesh)(GeometryHandle, nullptr, &NumVertices, nullptr, &NumTriangles);

  if (Result != ovrSuccess) {
    UE_LOG(LogAudio, Warning, TEXT("Failed getting simplified mesh from the audio propagation sub-system!"));
  } else {
    SimplifiedVertices.SetNum(NumVertices);
    SimplifiedIndices.SetNum(NumTriangles * 3);

    TArray<FVector3f> VertexArray;
    VertexArray.SetNum(NumVertices);

    Result = OVRA_CALL(ovrAudio_AudioGeometryGetSimplifiedMesh)(
        GeometryHandle, (float*)VertexArray.GetData(), &NumVertices, SimplifiedIndices.GetData(), &NumTriangles);
    if (Result != ovrSuccess) {
      UE_LOG(LogAudio, Warning, TEXT("Failed getting simplified mesh from the audio propagation sub-system!"));
    } else {
      for (size_t i = 0; i < NumVertices; i++) {
        SimplifiedVertices[i] = FDynamicMeshVertex(MetaXRAudioUtilities::ToUEVector3f(VertexArray[i]));
      }
    }
  }

  IPlatformFile& PlatformFile = FPlatformFileManager::Get().GetPlatformFile();
  FString FullFilePath = FPaths::ProjectContentDir() / FilePath;
  if (PlatformFile.FileExists(*FullFilePath)) {
    IFileHandle* FileHandle = PlatformFile.OpenRead(*FullFilePath);
    if (FileHandle) {
      DataSize = FileHandle->Size();
    }
    delete FileHandle;
  }
}

#endif // WITH_EDITOR

bool UMetaXRAcousticGeometry::ReadFile() {
  if (FilePath.IsEmpty()) {
    UE_LOG(LogAudio, Warning, TEXT("No geometry file path provided!"));
    return false;
  }

  if (MetaXRAudioUtilities::PlayModeActive(GetWorld())) {
    LoadGeometryAsync();
  } else {
    FString FullFilePath = FPaths::ProjectContentDir() / FilePath;
    if (!FPaths::FileExists(FullFilePath)) {
      UE_LOG(LogAudio, Warning, TEXT("Audio geometry file not found: %s"), *FullFilePath);
      return false;
    }

    // Read the file data into a byte array
    ovrResult Result = OVRA_CALL(ovrAudio_AudioGeometryReadMeshFile)(OvrGeometry, TCHAR_TO_UTF8(*FullFilePath));
    if (Result != ovrSuccess) {
      UE_LOG(LogAudio, Warning, TEXT("Unable to read audio geometry from file: %s"), *FullFilePath);
      return false;
    } else {
      UE_LOG(LogAudio, Log, TEXT("Successfully read geometry from file: %s"), *FullFilePath);
    }

    Result = OVRA_CALL(ovrAudio_AudioGeometrySetObjectFlag)(OvrGeometry, ovrAudioObjectFlag_Enabled, true);
    Result = OVRA_CALL(ovrAudio_AudioGeometrySetObjectFlag)(OvrGeometry, ovrAudioObjectFlag_Static, IsStatic());
  }

#if WITH_EDITOR
  UpdateGizmoMesh();
#endif
  return true;
}

bool UMetaXRAcousticGeometry::WriteFile() {
  // Create a temporary geometry.
  ovrAudioGeometry tempGeometryHandle;
  ovrResult Result = OVRA_CALL(ovrAudio_CreateAudioGeometry)(CachedContext, &tempGeometryHandle);
  if (Result != ovrSuccess) {
    UE_LOG(LogAudio, Warning, TEXT("Unable to create temp audio geometry"));
    return false;
  } else {
    UE_LOG(LogAudio, Log, TEXT("Created new temporary geometry handle %p"), tempGeometryHandle);
  }

  // Upload the mesh geometry and then write the result to disk
  bool Succeeded = false;
  if (UploadMesh(tempGeometryHandle)) {
    if (WriteFileInternal(tempGeometryHandle)) {
      Succeeded = true;
    }
  }

  // Destroy the geometry.
  UE_LOG(LogAudio, Log, TEXT("Destroying temporary geometry handle %p"), tempGeometryHandle);
  if (OVRA_CALL(ovrAudio_DestroyAudioGeometry)(tempGeometryHandle) != ovrSuccess) {
    UE_LOG(LogAudio, Warning, TEXT("Failed to destroy temp geometry handle"));
    Succeeded = false;
  }

  return Succeeded;
}

bool UMetaXRAcousticGeometry::WriteFileInternal(ovrAudioGeometry GeometryHandle) {
  // Setup the filepaths for the output file
#if WITH_EDITOR
  GenerateFileNameIfEmpty();
#endif
  FString FullFilePath = FPaths::ProjectContentDir() / FilePath;
#if WITH_EDITOR
  MetaXRAudioUtilities::CreateMetaXRAcousticContentDirectory(FPaths::GetPath(FilePath));
#endif

  // Write the mesh to a file.
  ovrResult Result = OVRA_CALL(ovrAudio_AudioGeometryWriteMeshFile)(GeometryHandle, TCHAR_TO_ANSI(*FullFilePath));
  if (Result != ovrSuccess) {
    UE_LOG(LogAudio, Warning, TEXT("Unable to save geometry to file"));
  } else {
    UE_LOG(LogAudio, Display, TEXT("Successfully wrote geometry to file: %s"), *FullFilePath);
  }

#if WITH_EDITOR
  UpdateGizmoMesh(GeometryHandle);
#endif

  if (!bFileEnabled) {
    UE_LOG(LogAudio, Warning, TEXT("File Successfully written but File Enabled is off, turn it on to use file"));
  }

  IPlatformFile& PlatformFile = FPlatformFileManager::Get().GetPlatformFile();
  if (PlatformFile.FileExists(*FullFilePath)) {
    IFileHandle* FileHandle = PlatformFile.OpenRead(*FullFilePath);
    if (FileHandle) {
      DataSize = FileHandle->Size();
    }
    delete FileHandle;
  }

  return true;
}

void UMetaXRAcousticGeometry::LoadGeometryAsync() {
  FString FullFilePath = FPaths::ProjectContentDir() / FilePath;
#if WITH_EDITOR
  if (!FPaths::FileExists(FullFilePath)) {
    UE_LOG(LogAudio, Warning, TEXT("Audio geometry file not found: %s"), *FullFilePath);
    return;
  }
#endif

  // Read the file data into a byte array
  TArray<uint8> FileData;
  if (!FFileHelper::LoadFileToArray(FileData, *FullFilePath)) {
    UE_LOG(LogAudio, Warning, TEXT("Failed to load audio geometry file: %s"), *FullFilePath);
    return;
  }

  ovrResult Result = OVRA_CALL(ovrAudio_AudioGeometryReadMeshMemory)(OvrGeometry, (const int8_t*)FileData.GetData(), FileData.Num());
  if (Result != ovrSuccess) {
    UE_LOG(LogAudio, Warning, TEXT("Unable to read audio geometry from memory: %s"), *FullFilePath);
    return;
  } else {
    UE_LOG(LogAudio, Log, TEXT("Successfully read audio geometry from memory: %s"), *FullFilePath);
  }

  Result = OVRA_CALL(ovrAudio_AudioGeometrySetObjectFlag)(OvrGeometry, ovrAudioObjectFlag_Enabled, true);
  ApplyTransform();
  Result = OVRA_CALL(ovrAudio_AudioGeometrySetObjectFlag)(OvrGeometry, ovrAudioObjectFlag_Static, IsStatic());

#if WITH_EDITOR
  UpdateGizmoMesh();
#endif
}

void UMetaXRAcousticGeometry::PostLoad() {
  Super::PostLoad();

#if WITH_EDITOR
  if (!MetaXRAudioUtilities::PlayModeActive(GetWorld())) {
    DestroyInternal();
  }
#endif
}

void UMetaXRAcousticGeometry::BeginDestroy() {
  Super::BeginDestroy();

  if (OvrGeometry != nullptr && CachedContext != nullptr) {
    DestroyInternal();
  }
}

void UMetaXRAcousticGeometry::DestroyComponent(bool bPromoteChildren) {
  Super::DestroyComponent(bPromoteChildren);
}

#if COMPILE_AS_DEBUG_MODE
#pragma optimize("", on) // PAS - TEMP - DELETE THIS - better debugging
#endif

void UMetaXRAcousticGeometry::Activate(bool bReset) {
  if (OvrGeometry == nullptr) {
    return;
  }

  ovrResult Result = OVRA_CALL(ovrAudio_AudioGeometrySetObjectFlag)(OvrGeometry, ovrAudioObjectFlag_Enabled, true);
  ApplyTransform();
  Result = OVRA_CALL(ovrAudio_AudioGeometrySetObjectFlag)(OvrGeometry, ovrAudioObjectFlag_Static, IsStatic());
  UE_LOG(LogAudio, Log, TEXT("Set transform and activated for geometry %p"), OvrGeometry);

  // Ensure project settings are applied for geometry
  const UMetaXRAcousticProjectSettings* Settings = GetDefault<UMetaXRAcousticProjectSettings>();
  Result = OVRA_CALL(ovrAudio_Enable)(CachedContext, ovrAudioEnable_Diffraction, Settings->bDiffractionEnabled);
  OVR_AUDIO_CHECK(Result, "Failed to set diffraction enabled");
  Result = OVRA_CALL(ovrAudio_SetAcousticModel)(CachedContext, static_cast<ovrAudioAcousticModel>(Settings->AcousticModel));
  OVR_AUDIO_CHECK(Result, "Failed to set acoustic model");
}

void UMetaXRAcousticGeometry::Deactivate() {
  if (OvrGeometry == nullptr) {
    return;
  }

  ovrResult Result = OVRA_CALL(ovrAudio_AudioGeometrySetObjectFlag)(OvrGeometry, ovrAudioObjectFlag_Enabled, true);
  ApplyTransform();
  Result = OVRA_CALL(ovrAudio_AudioGeometrySetObjectFlag)(OvrGeometry, ovrAudioObjectFlag_Static, IsStatic());
  UE_LOG(LogAudio, Log, TEXT("Set transform and deactivated for geometry %p"), OvrGeometry);
}

#if WITH_EDITOR
void UMetaXRAcousticGeometry::PostEditChangeProperty(struct FPropertyChangedEvent& PropertyChangedEvent) {
  CheckGeoTransformValid();
  // Must be called after our updated above in order to make sure everythings updated correctly.
  Super::PostEditChangeProperty(PropertyChangedEvent);
}
#endif

FPrimitiveSceneProxy* UMetaXRAcousticGeometry::CreateSceneProxy() {
#if WITH_EDITOR_GIZMOS
  return new FMetaXRAcousticGeometrySceneProxy(this);
#else
  return nullptr;
#endif
}

// This function tells the renderer where the geometry is so it can only render it while in frame
FBoxSphereBounds UMetaXRAcousticGeometry::CalcBounds(const FTransform& LocalToWorld) const {
  FBoxSphereBounds GeometryBounds = Super::CalcBounds(LocalToWorld);

  // Collect all the meshes and landscapes associated with this geometry
  FMeshGatherer Gatherer = FMeshGatherer(false, LOD);
  TArray<UMetaXRAcousticMaterial*> CurrentMaterials;
  TraverseMeshHierarchy(GetOwner(), bIncludeChildren, GetExcludeTags(), false, LOD, Gatherer, &CurrentMaterials);

  // Update the counts for all static meshes
  for (FMeshMaterial& MeshMaterial : Gatherer.GetMeshes()) {
    GeometryBounds = GeometryBounds +
        MeshMaterial.StaticMesh->GetStaticMesh()->GetBounds().TransformBy(MeshMaterial.StaticMesh->GetComponentTransform());
  }

#if WITH_EDITOR
  // Update the counts for all landscapes
  for (FLandscapeMaterial& LandscapeMaterial : Gatherer.GetTerrains()) {
    for (auto It = LandscapeMaterial.LandscapeInfo->XYtoComponentMap.CreateIterator(); It; ++It) {
      ULandscapeComponent* Component = It.Value();
      GeometryBounds = GeometryBounds + Component->Bounds.TransformBy(Component->GetComponentTransform());
    }
  }
#endif

  return GeometryBounds;
}

FMetaXRAcousticGeometrySceneProxy::FMetaXRAcousticGeometrySceneProxy(const UPrimitiveComponent* InComponent)
    : FDebugRenderSceneProxy(InComponent) {
  GeometryComponent = Cast<UMetaXRAcousticGeometry>(InComponent);
}

FPrimitiveViewRelevance FMetaXRAcousticGeometrySceneProxy::GetViewRelevance(const FSceneView* View) const {
  IConsoleVariable* MetaXRAudioGizmoCVAR = IConsoleManager::Get().FindConsoleVariable(TEXT("MetaXRAudioGizmos"));
  bool bVisible = MetaXRAudioGizmoCVAR->GetInt() != 0;
  FPrimitiveViewRelevance Result;
  Result.bDrawRelevance = bVisible;
  Result.bDynamicRelevance = true;
  return Result;
}

void FMetaXRAcousticGeometrySceneProxy::GetDynamicMeshElements(
    const TArray<const FSceneView*>& Views,
    const FSceneViewFamily& ViewFamily,
    uint32 VisibilityMap,
    FMeshElementCollector& Collector) const {
  // Set up material for wireframe rendering
  FColoredMaterialRenderProxy* WireframeMaterialInstance =
      new FColoredMaterialRenderProxy(GEngine->WireframeMaterial->GetRenderProxy(), FLinearColor::Yellow);

  // Add the wireframe material to the collector
  Collector.RegisterOneFrameMaterialProxy(WireframeMaterialInstance);

  for (int32 ViewIndex = 0; ViewIndex < Views.Num(); ViewIndex++) {
    if (VisibilityMap & (1 << ViewIndex)) {
      const FSceneView* View = Views[ViewIndex];
      FDynamicMeshBuilder MeshBuilder(View->GetFeatureLevel());
      MeshBuilder.AddVertices(GeometryComponent->SimplifiedVertices);
      MeshBuilder.AddTriangles(GeometryComponent->SimplifiedIndices);

      // Add mesh to the collector
      MeshBuilder.GetMesh(GetLocalToWorld(), WireframeMaterialInstance, SDPG_World, false, false, false, ViewIndex, Collector);
    }
  }
}
